name: Drift Check
on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch: {}
jobs:
  drift:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Terragrunt
        run: |
          TG_VERSION=$(curl -s https://api.github.com/repos/gruntwork-io/terragrunt/releases/latest | grep tag_name | cut -d '"' -f4)
          curl -L https://github.com/gruntwork-io/terragrunt/releases/download/${TG_VERSION}/terragrunt_linux_amd64 -o terragrunt
          sudo install terragrunt /usr/local/bin/terragrunt
      - name: Read-only plan all
        run: |
          terragrunt run-all init -upgrade || true
          terragrunt run-all plan || true
