name: Terraform Reusable
on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string
jobs:
  tf:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Fmt & Validate
        run: |
          cd ${{ inputs.working-directory }}
          terraform fmt -check -recursive || true
          terraform init -backend=false
          terraform validate
      - name: TFLint
        uses: terraform-linters/setup-tflint@v4
      - name: Run TFLint
        run: |
          cd ${{ inputs.working-directory }}
          tflint --init
          tflint -f sarif > tflint.sarif || true
      - name: Upload TFLint SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ inputs.working-directory }}/tflint.sarif
